### ISSUE TITLE
associations des mot clés de bar avec leur nom à afficher dans les mails

### ISSUE THREAD

**Issue by pjoubert-** [TaTaaaa/tofbot#1]
Les commandes supportent plusieurs appellations pour un même lieu, néanmoins, on souhaite avoir une jolie formulation dans les mails.

Une solution peut être d'associer les mots clés utilisés à une clé, qui elle identifie la chaîne à utiliser dans le mail.

exemple:

clef_bar["keepitweird"] = "kiw"
clef_bar["kiw"] = "kiw"

joli_nom["kiw"] = "Keep It Weird"

L'appel de la valeur de joli_nom se faisant avec joli_nom[clef]

**Comment by TaTaaaa** [comment]
Fait dans le commit #27

pas exactement pareil, coudonc!
[https://github.com/soulaklabs/tofbot/pull/27/commits/1e56439694bcac18929fa4877ff7fe867417c491](url)
