### ISSUE TITLE
limiter l'envoi de mails pour ne pas spammer la liste

### ISSUE THREAD

**Issue by pjoubert-** [TaTaaaa/tofbot#2]
Dans un souci évident de respect pour autrui et parce qu'on sait tous qu'on est joueur, il faut limiter le nombre d'emails envoyés sur la liste à un par jour

**Comment by TaTaaaa** [comment]
fait sur le commit:
https://github.com/TaTaaaa/tofbot/commit/a506e8e727bfebff87f5dc0d024a743edae8a66c
