### ISSUE TITLE
anonymiser à l'aide de hash

### ISSUE THREAD

**Issue by pjoubert-** [TaTaaaa/tofbot#3]
utiliser une fonction de hashage sur les nickname afin de ne pas les retrouver dans le code

exemple:

`if sha256(msg.nick) == nickhash:
   irc.msg("coucou %s" % msg.nick)`

**Comment by TaTaaaa** [comment]
fait sur le commit:
https://github.com/TaTaaaa/tofbot/commit/8c8a4d4dc2b7bc069f4ab773e8d73f4fd67d4de9
